# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'testingWithQuick' do
# Comment this line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!

# Pods for testingWithQuick

def testing_pods
    pod 'Quick'
    pod 'Nimble'
end

target 'testingWithQuickTests' do
    inherit! :search_paths
    # Pods for testing
    testing_pods
  end

end
